# Generated by Django 5.1.1 on 2024-11-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_color_size_productcolors_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolors',
            name='stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
