# Generated by Django 5.1.1 on 2024-11-22 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
