# Generated by Django 5.1.1 on 2024-11-23 19:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_collection_theme_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
