# Generated by Django 5.1.1 on 2024-11-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_theme_meta_theme_slug_alter_theme_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='display_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
