# Generated by Django 5.1.1 on 2024-11-23 19:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_theme_display_in_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='highlights',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='materials_craftsmanship',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='occasion',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
