# Generated by Django 5.1.1 on 2024-11-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_collection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='display_in_home',
            field=models.BooleanField(default=True),
        ),
    ]
