# Generated by Django 5.1.1 on 2024-11-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_homepagebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebanner',
            name='tagline',
            field=models.CharField(default=1, max_length=1255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
