# Generated by Django 5.1.1 on 2024-11-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_product_best_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestSeller',
        ),
    ]
