# Generated by Django 5.1.1 on 2024-11-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_delete_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
