# Generated by Django 5.1.1 on 2024-11-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_product_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couponcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('valid_upto', models.DateField()),
                ('flat_discount', models.IntegerField(blank=True, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('percentage_max_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='coupon_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='order_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
