# Generated by Django 5.1.1 on 2024-11-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_customer_session_id_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='max_redeem_limit',
            field=models.IntegerField(default=1),
        ),
    ]
