# Generated by Django 3.2 on 2024-11-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_couponcodeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='final_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
