# Generated by Django 5.1.1 on 2025-02-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inspiritation',
            field=models.BooleanField(default=False),
        ),
    ]
